name: Test Automation Workflow

on:
  schedule: 
  - cron: 00 18 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation framework with maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=true
    - name: Upload test logs
      if: always()
      uses: actions/upload-artifact@v5.0.0
      with: 
        name: Test logs
        path: logs/

    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v5.0.0
      with: 
        name: screenshots
        path: screenshots/
        
    - name: Upload HTML report as Artifacts
      if: always()
      uses: actions/upload-artifact@v5.0.0
      with: 
        name: html-report
        path: report.html

      
    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v5.0.0
      with: 
        name: Test reports
        path: report.html
      
    - name: Test Execution status
      run: echo "Test Execution Completed"

    - name: Copy Report to gh-pages Folder
    if: always()
    
    run: |
      mkdir -p public/extent-reports
      cp -R report.html public/extent-reports
      cp -R screenshots/ public/extent-reports/screenshots/
      ls -l 

    
     - name: Deploy
     if: always()
     uses: JamesIves/github-pages-deploy-action@v5.0.0
     with: 
       folder: public/extent-reports/
       token: ${{ secrets.Test}}
       clean: true
    
    

      
       
       
